name: circle_flags
description: A collection of circular flags.
version: 1.0.0
repository: https://github.com/benjamin-otto/flutter_circle_flags

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flag_builder:
    path: ./packages/flag_builder
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/svg/country_flags/
    - assets/svg/language_flags/
    - assets/svg/other_flags/
