name: flag_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.4

dependencies:
  build: ^2.4.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
